### ISSUE TITLE
npm audit reveals a vulnerability in lodash version.

### ISSUE THREAD

**Issue by manuhank** [victorhahn/airtable-plus#3]
After installing NPM found a vulnerability not automatically fixable:
>High            Prototype Pollution                                           
  Package         lodash                                                        
  Patched in      >=4.17.12                                                     
  Dependency of   airtable-plus                                                 
  Path           airtable-plus > airtable > lodash                             
  More info       https://nodesecurity.io/advisories/1065

**Comment by cjsturgess** [comment]
@victorhahn just a heads up, I submitted a PR that should address this.
