### ISSUE TITLE
Update airtable dependency to 0.7.2

### ISSUE THREAD

**Issue by will-e-yams** [victorhahn/airtable-plus#6]
> Airtable.js had a medium-severity security bug when used in Node.js. Prior to this version, Airtable.js could connect to a server with an invalid SSL/TLS certificate. This means that Airtable.js was vulnerable to man-in-the-middle attacks. Airtable.js used in browser was not affected.

> This bug has been patched in the latest version, v0.7.2, and we strongly suggest that you upgrade. As an added precaution, it is best practice to change any API keys you are using.

https://github.com/Airtable/airtable.js/releases/tag/v0.7.2

**Comment by cjsturgess** [comment]
Looks like this was patched in #5.

**Comment by will-e-yams** [comment]
Covered by PR #5
